| 2023-01-07 23:24:05,317 – [INFO]: Попытка подключения к postgres. Исполняемый файл – 'postgres_client.py': функция – 'connect'(29)
| 2023-01-07 23:24:05,401 – [INFO]: Успешное подключение к postgres. Исполняемый файл – 'postgres_client.py': функция – 'connect'(33)
| 2023-01-07 23:24:05,401 – [INFO]: Попытка подключения к Elasticsearch. Исполняемый файл – 'elasticsearch_client.py': функция – 'connect'(35)
| 2023-01-07 23:24:05,429 – [INFO]: Подключение к Elasticsearch: True. Исполняемый файл – 'elasticsearch_client.py': функция – 'connect'(37)
| 2023-01-07 23:24:06,730 – [DEBUG]: Индекс movies создан. Ответ Elasticsearch: {'acknowledged': True, 'shards_acknowledged': True, 'index': 'movies'}. Исполняемый файл – 'movies_helpers.py': функция – 'create_index_if_not_exists'(38)
| 2023-01-07 23:24:06,749 – [DEBUG]: Создан новый курсор для Postgres. Исполняемый файл – 'postgres_client.py': функция – 'connect'(78)
| 2023-01-07 23:24:06,749 – [DEBUG]: Файл /Users/madihanagatanov/middle_code/new_admin_panel_sprint_3/etl/state/state.json не может быть прочитан. Произошла ошибка: Expecting value: line 1 column 1 (char 0).. Исполняемый файл – 'storage.py': функция – 'retrieve_state'(45)
| 2023-01-07 23:24:06,932 – [DEBUG]: Файл /Users/madihanagatanov/middle_code/new_admin_panel_sprint_3/etl/state/state.json не может быть прочитан. Произошла ошибка: Expecting value: line 1 column 1 (char 0).. Исполняемый файл – 'storage.py': функция – 'retrieve_state'(45)
| 2023-01-07 23:24:06,932 – [INFO]: Успешно загружено 100 объектов. Исполняемый файл – 'validators.py': функция – 'validate_film_works'(29)
| 2023-01-07 23:24:07,651 – [INFO]: Успешно загружено 200 объектов. Исполняемый файл – 'validators.py': функция – 'validate_film_works'(29)
| 2023-01-07 23:24:08,721 – [INFO]: Успешно загружено 300 объектов. Исполняемый файл – 'validators.py': функция – 'validate_film_works'(29)
| 2023-01-07 23:24:09,760 – [INFO]: Успешно загружено 400 объектов. Исполняемый файл – 'validators.py': функция – 'validate_film_works'(29)
| 2023-01-07 23:24:10,808 – [INFO]: Успешно загружено 500 объектов. Исполняемый файл – 'validators.py': функция – 'validate_film_works'(29)
| 2023-01-07 23:24:11,866 – [INFO]: Успешно загружено 600 объектов. Исполняемый файл – 'validators.py': функция – 'validate_film_works'(29)
| 2023-01-07 23:24:12,950 – [INFO]: Успешно загружено 700 объектов. Исполняемый файл – 'validators.py': функция – 'validate_film_works'(29)
| 2023-01-07 23:24:13,984 – [INFO]: Успешно загружено 800 объектов. Исполняемый файл – 'validators.py': функция – 'validate_film_works'(29)
| 2023-01-07 23:24:15,022 – [INFO]: Успешно загружено 900 объектов. Исполняемый файл – 'validators.py': функция – 'validate_film_works'(29)
| 2023-01-07 23:24:16,079 – [INFO]: Успешно загружено 999 объектов. Исполняемый файл – 'validators.py': функция – 'validate_film_works'(29)
| 2023-01-07 23:24:16,080 – [ERROR]: Произошла ошибка при валидации фильмов из PostgreSQL. ['e72208b6-7181-49eb-9c25-2bc54629b21d']. Подробности: etl_status/state.json. Исполняемый файл – 'validators.py': функция – 'validate_film_works'(31)
| 2023-01-07 23:24:17,125 – [DEBUG]: Postgres cursor закрыт. Исполняемый файл – 'postgres_client.py': функция – 'close'(93)
| 2023-01-07 23:24:17,129 – [INFO]: Соединение закрыто для ElasticsearchClient. Исполняемый файл – 'base_client.py': функция – 'close'(60)
| 2023-01-07 23:24:17,129 – [INFO]: Соединение закрыто для PostgresClient. Исполняемый файл – 'base_client.py': функция – 'close'(60)
| 2023-01-07 23:24:17,130 – [INFO]: Остановка процесса на 5 минут. Исполняемый файл – 'main.py': функция – 'main'(18)
